[book]
authors = ["Karan Sharma"]
language = "en"
multilingual = false
src = "src"
title = "Kubernetes - Production Deployments for Developers"
description = "Recommendations for secure applications development with Rust"

# [preprocessor.checklist]
# title = "Recommendations checklist"