[book]
authors = ["Karan Sharma"]
language = "en"
multilingual = false
src = "src"
title = "Kubernetes - Production Deployments for Developers"
description = "A mini guide for developers to deploy applications on Kubernetes"
